version: '3.7'
services:
  authorization-server:
    container_name: authorization-server
    image: adoptopenjdk:11.0.10_9-jdk-openj9-0.24.0
    volumes:
      - './authorization-server/build/libs/authorization-server-1.0.0.BUILD-SNAPSHOT.jar:/var/authorization/authorization-server.jar'
      - './authorization-server/build/resources/main/certificate/authorization.jks:/var/authorization/certificate/authorization.jks'
    ports:
      - 8080:8080
    command: "java -Xmx256m -Xms256m -Dfile.encoding=UTF-8 -Duser.timezone=GMT+9 -Dspring.profiles.active=prod,log -jar /var/authorization/authorization-server.jar"