version: '3.7'
services:
  authorization-server:
    container_name: authorization-server
    image: adoptopenjdk:11.0.10_9-jdk-openj9-0.24.0
    volumes:
      - './build/libs/authorization-1.0.0.BUILD-SNAPSHOT.jar:/var/authorization-server/authorization.jar'
      - './build/resources/main/certificate/authorization.jks:/var/authorization-server/certificate/authorization.jks'
    ports:
      - 8080:8080
    command: "java -Xmx256m -Xms256m -Dfile.encoding=UTF-8 -Duser.timezone=GMT+9 -Dspring.profiles.active=prod -jar /var/authorization-server/authorization.jar"